name: Deploy

on:
  push:
    branches:
      - master
      - steve/adding-cdk-to-automate-provisioning

jobs:
  Deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
#        - name: Install Node.js
#          uses: actions/setup-node@v4
#          with:
#            node-version: '20.x'
#        - name: Install npm dependencies and build for backend and client
#          run: npm run build
        - name: Deploy to Server
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}
            REMOTE_USER: ec2-user
            TARGET: /home/ec2-user/app
            EXCLUDE: "/.git/, /node_modules/, /backend/node_modules/, /client/node_modules/, /.github/, /cdk/"
        - name: Setup NGINX and start API
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_PUBLIC_IP }}
            username: ec2-user
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script_stop: true
            script: |
              whoami
              ls -al
              cd /home/ec2-user/app
              npm build
