name: Deploy

on:
  push:
    branches:
      - master
      - steve/adding-cdk-to-automate-provisioning

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Deploy over SSH
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_PUBLIC_IP }}
          REMOTE_USER: ec2-user
          SCRIPT_AFTER: |
            ./script
            echo "hey this worked"
            cd /home/ec2-user
            git clone git@github.com:annaharbour/Blend.git the-app